export interface Stock {
  symbol: string;
  name?: string;
  addedAt?: number; // timestamp
}

export const DEFAULT_STOCKS: Stock[] = [
  { symbol: 'ABNB', name: 'Airbnb' },
  { symbol: 'BABA', name: 'Alibaba' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: 'AMD', name: 'AMD' },
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'ACB', name: 'Aurora Cannabis' },
  { symbol: 'BIDU', name: 'Baidu' },
  { symbol: 'BASFY', name: 'BASF' },
  { symbol: 'BLK', name: 'BlackRock' },
  { symbol: 'SQ', name: 'Block' },
  { symbol: 'AVGO', name: 'Broadcom' },
  { symbol: 'AI', name: 'C3.ai' },
  { symbol: 'CGC', name: 'Canopy Growth' },
  { symbol: 'CAT', name: 'Caterpillar' },
  { symbol: 'NET', name: 'Cloudflare' },
  { symbol: 'KO', name: 'Coca Cola' },
  { symbol: 'COIN', name: 'Coinbase' },
  { symbol: '^GDAXI', name: 'DAX' },
  { symbol: 'DIS', name: 'Disney' },
  { symbol: 'EBAY', name: 'eBay' },
  { symbol: 'FI', name: 'Fiserv' },
  { symbol: '^HSI', name: 'Hang Seng' },
  { symbol: 'ILMN', name: 'Illumina' },
  { symbol: 'INTC', name: 'Intel' },
  { symbol: 'JAZZ', name: 'Jazz Pharmaceuticals' },
  { symbol: 'JD', name: 'JD.com' },
  { symbol: 'LUMN', name: 'Lumen' },
  { symbol: 'MRVL', name: 'Marvell Technology' },
  { symbol: 'META', name: 'Meta' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: '^IXIC', name: 'NASDAQ' },
  { symbol: 'NKE', name: 'Nike' },
  { symbol: 'NIO', name: 'NIO' },
  { symbol: 'NVO', name: 'Novo Nordisk' },
  { symbol: 'NVDA', name: 'NVIDIA' },
  { symbol: 'OCGN', name: 'Ocugen' },
  { symbol: 'PYPL', name: 'PayPal' },
  { symbol: 'PM', name: 'Philip Morris' },
  { symbol: 'QCOM', name: 'Qualcomm' },
  { symbol: 'RHM.DE', name: 'Rheinmetall' },
  { symbol: 'SAP', name: 'SAP' },
  { symbol: 'SNOW', name: 'Snowflake' },
  { symbol: '^GSPC', name: 'S&P 500' },
  { symbol: 'SPOT', name: 'Spotify' },
  { symbol: 'SBUX', name: 'Starbucks' },
  { symbol: 'SMSI', name: 'Suess MicroTec' },
  { symbol: 'TDOC', name: 'Teladoc Health' },
  { symbol: '0700.HK', name: 'Tencent Holdings' },
  { symbol: 'TME', name: 'Tencent Music' },
  { symbol: 'TSLA', name: 'Tesla' },
  { symbol: 'UBER', name: 'Uber Technologies' },
  { symbol: 'UAA', name: 'Under Armour' },
  { symbol: 'UNH', name: 'United Health' },
  { symbol: 'WBD', name: 'Warner Bros Discovery' },
  { symbol: '2269.HK', name: 'Wuxi Biologics' },
  { symbol: '1810.HK', name: 'Xiaomi' },
  { symbol: 'XPEV', name: 'XPeng' },
  { symbol: 'ZAL.DE', name: 'Zalando' }
];
